# -*- coding: utf-8 -*-
"""Breast Cancer Classification using Machine Learning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1885qkUJcgQyRyBkp1K9l2YrQDxeEO4C8
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading the csv data to a Pandas DataFrame
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()
#

print(breast_cancer_dataset)

data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

data_frame.head()

# adding the 'target' column to the data frame
data_frame['label'] = breast_cancer_dataset.target

data_frame.head()

data_frame.shape

#Getting some information about the data
data_frame.info()

#Checking the missing values

data_frame.isnull().sum()

#Statistical measure of the dataset
data_frame.describe()

#checking the distribution of target variable

data_frame['label'].value_counts()

"""1 ----> Benign
0 ----> Malignant
"""

data_frame.groupby('label').mean()

"""Seperating the features and target"""

x = data_frame.drop(columns='label', axis=1)
y = data_frame['label']

print(x)

print(y)

#Splitting the data into training data and testing data

X_train,X_test,Y_train,Y_Test = train_test_split(x,y,test_size=0.2,random_state=2)

print(X_train.shape)
print(X_test.shape)
print(Y_Test.shape)

"""Model Training"""

model = LogisticRegression()

#training the logistic regression model using training data

model.fit(X_train,Y_train)

"""Model evaluation

Accuracy score
"""

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train,X_train_prediction)

training_data_accuracy

accuarcy_score_training = model.score(X_train,Y_train) #Accuracy is training data

accuarcy_score_training

accuarcy_score_test = model.score(X_test,Y_Test) #Accuracy is test data

accuarcy_score_test

"""Building a predictive system"""

input_data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one datapoint
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

if prediction[0] == 0:
    print('The breast cancer is Malignant')
else:
    print('The breast cancer is Benign')