# -*- coding: utf-8 -*-
"""Clustering_KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16diwo5PxGCE8UokB8-RKq55JeWwup5eF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans

df=pd.read_csv('Mall_Customers.csv')

df.head()

plt.figure(figsize=(10,6))
plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'])
plt.xlabel('Annual Income (k$)')
plt.ylabel('Clusering cx data)')
plt.show()

X=df.iloc[:,[3,4]].values
X[:5]

clustering_scores=[]

for i in range(1,21):
    kemeans=KMeans(n_clusters=i,init='random',random_state=42)
    kemeans.fit(X)
    clustering_scores.append(kemeans.inertia_)

plt.figure(figsize=(10,6))
plt.plot(range(1,21),clustering_scores,marker=".")
plt.xlabel('Number of clusters')
plt.ylabel('WCSS score')
plt.title("Elbow method")
plt.scatter(5,clustering_scores[4],s=100,c='red',marker='*')
plt.show()

clustering_scores

kemeans=KMeans(n_clusters=5,random_state=42)
kemeans.fit(X)
pred=kemeans.predict(X)
pred

df['Cluster']=pd.DataFrame(pred,columns=['Cluser'])
df.head()

print('No of customers in each segments:', df["Cluster"].value_counts())

plt.figure(figsize=(10,6))

plt.scatter(X[pred==0,0],X[pred==0,1],c="brown",label='Cluster 0')
plt.scatter(X[pred==1,0],X[pred==1,1],c="green",label='Cluster 1')
plt.scatter(X[pred==2,0],X[pred==2,1],c="blue",label='Cluster 2')
plt.scatter(X[pred==3,0],X[pred==3,1],c="purple",label='Cluster 3')
plt.scatter(X[pred==4,0],X[pred==4,1],c="orange",label='Cluster 4')

plt.scatter(kemeans.cluster_centers_[:,0],kemeans.cluster_centers_[:,1],s=300,c='red',marker='*',label='Centroids')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

X=df.iloc[:,[2,3,4]].values
X[:5]

clustering_scores=[]

for i in range(1,21):
    kemeans=KMeans(n_clusters=i,init='random',random_state=42)
    kemeans.fit(X)
    clustering_scores.append(kemeans.inertia_)

plt.figure(figsize=(10,6))
plt.plot(range(1,21),clustering_scores,marker=".")
plt.xlabel('Number of clusters')
plt.ylabel('WCSS score')
plt.title("Elbow method")
plt.scatter(6,clustering_scores[5],s=100,c='red',marker='*')
plt.show()

kemeans=KMeans(n_clusters=6,random_state=42)
kemeans.fit(X)
pred=kemeans.predict(X)
pred

df['Cluster']=pd.DataFrame(pred,columns=['Cluser'])
df.head()

print('No of customers in each segments:', df["Cluster"].value_counts())

fig=plt.figure(figsize=(15,15))
ax=fig.add_subplot(111,projection='3d')

plt.scatter(X[pred==0,0],X[pred==0,1],c="brown",s=100,label='Cluster 0')
plt.scatter(X[pred==1,0],X[pred==1,1],c="green",s=100,label='Cluster 1')
plt.scatter(X[pred==2,0],X[pred==2,1],c="blue",s=100,label='Cluster 2')
plt.scatter(X[pred==3,0],X[pred==3,1],c="purple",s=100,label='Cluster 3')
plt.scatter(X[pred==4,0],X[pred==4,1],c="orange",s=100,label='Cluster 4')
plt.scatter(X[pred==5,0],X[pred==5,1],c="red",s=100,label='Cluster 5')

plt.scatter(kemeans.cluster_centers_[:,0],kemeans.cluster_centers_[:,1],s=300,c='red',marker='*',label='Centroids')
ax.set_xlabel('Age')
ax.set_ylabel('Annual Income (k$)')
ax.set_zlabel('Spending Score (1-100)')
plt.legend()
plt.show()