# -*- coding: utf-8 -*-
"""Movie recommendation system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctT2W1P6nwQCQMj8_aXR2smugSTdD35o
"""

#Importing dependencies
import numpy as np
import pandas as pd
import difflib #get the closest match
from sklearn.feature_extraction.text import TfidfVectorizer#convert the text data into vectorized format
from sklearn.metrics.pairwise import cosine_similarity

"""Data collection and preprocessing"""

#Loadinfg the data from CSV file into pandas DF

movies_data = pd.read_csv('movies.csv')

#printing the first 5 rows of the DF

movies_data.head()

movies_data.shape

#Selecting the relevant features

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

#replacing the null values with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

#combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

combined_features

"""Converting the text data into feature vectors"""

vectorized = TfidfVectorizer()

feature_vector = vectorized.fit_transform(combined_features)

print(feature_vector)

"""Cosine similarity"""

#getting the similarity score using Cosine similarity

similarity = cosine_similarity(feature_vector)

print(similarity)

similarity.shape

#getting the movie name from the user

movie_name = input('Enter the favorite movie name: ')

#creating the list of all the movies given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

#finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

close_match = find_close_match[0]
print(close_match)

#find the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

#Getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

len(similarity_score)

#Sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print(sorted_similar_movies)

#print the name of similar movies based on index.

print('Movies suggested for you: \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data['index'] == index]['title'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1

"""Movie recommendar system"""

movie_name = input('Enter the favorite movie name: ')


list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1],reverse = True)

print('Movies suggested for you: \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data['index'] == index]['title'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1